#!/usr/bin/env python3
"""Render a 3wagent Markdown report.

Thin orchestration layer — delegates to build_markdown. PDF conversion is
available via --pdf but is not generated by default.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from build_markdown import build_markdown, local_now, slugify_topic, write_markdown
from progress import complete_run

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TEMPLATE = ROOT / "templates" / "report.md"
DEFAULT_OUTPUT_ROOT = ROOT / "reports"
DEFAULT_VIEWER_ROOT = ROOT / "viewer"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, help="Existing Markdown file to archive.")
    parser.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    parser.add_argument("--title", default="3wagent Policy Report")
    parser.add_argument("--topic", help="Topic slug or report folder suffix.")
    parser.add_argument("--date", help="Report date in YYYYMMDD format.")
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--viewer-root", type=Path, default=DEFAULT_VIEWER_ROOT)
    parser.add_argument("--update-viewer", action="store_true", default=True)
    parser.add_argument("--no-update-viewer", dest="update_viewer", action="store_false")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--run-id", help="Optional run id to mark as completed after archiving.")
    parser.add_argument("--pdf", action="store_true", help="Also convert the report to PDF.")
    parser.add_argument("--print-json", action="store_true")
    return parser.parse_args(argv)


def update_viewer_index(output_root: Path, viewer_root: Path) -> Path:
    """Regenerate viewer/reports.json from all archived reports."""
    reports: list[dict] = []
    if output_root.exists():
        for report_dir in sorted(output_root.iterdir(), reverse=True):
            if not report_dir.is_dir():
                continue
            markdown_path = report_dir / "report.md"
            if not markdown_path.exists():
                continue
            report_id = report_dir.name
            date_match = re.match(r"^(\d{8})-(.+)$", report_id)
            date = date_match.group(1) if date_match else ""
            topic = date_match.group(2) if date_match else report_id
            pdf_path = report_dir / "report.pdf"
            reports.append(
                {
                    "id": report_id,
                    "date": date,
                    "topic": topic,
                    "markdown": str(markdown_path),
                    "pdf": str(pdf_path) if pdf_path.exists() else None,
                    "content": markdown_path.read_text(encoding="utf-8"),
                }
            )

    viewer_root.mkdir(parents=True, exist_ok=True)
    index_path = viewer_root / "reports.json"
    index_path.write_text(
        json.dumps(
            {"generated_at": local_now().isoformat(timespec="seconds"), "reports": reports},
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    return index_path


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    report_date = args.date or local_now().strftime("%Y%m%d")
    topic = slugify_topic(args.topic or args.title)
    report_dir = args.output_root / f"{report_date}-{topic}"

    markdown = build_markdown(args.source, args.template, args.title, topic, report_date)
    markdown_path = write_markdown(markdown, report_dir, args.overwrite)

    pdf_path: Path | None = None
    pdf_attempts: list[dict] = []
    if args.pdf:
        from convert_pdf import convert_to_pdf

        pdf_path, pdf_attempts = convert_to_pdf(markdown_path, report_dir / "report.pdf", args.title)

    viewer_path: Path | None = None
    if args.update_viewer:
        viewer_path = update_viewer_index(args.output_root, args.viewer_root)

    if args.run_id:
        try:
            complete_run(args.run_id, report_dir.name)
        except Exception:
            pass  # Run may not exist; do not fail report generation

    result = {
        "report_dir": str(report_dir),
        "markdown": str(markdown_path),
        "pdf": str(pdf_path) if pdf_path else None,
        "pdf_attempts": pdf_attempts,
        "viewer_index": str(viewer_path) if viewer_path else None,
        "run_id": args.run_id,
    }
    if args.print_json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(f"Markdown: {markdown_path}")
        if args.pdf:
            print(f"PDF: {pdf_path if pdf_path else 'not generated'}")
            for attempt in pdf_attempts:
                status = "ok" if attempt["ok"] else "failed"
                print(f"- {attempt['converter']}: {status}: {attempt['message']}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
